class_name InfoData
extends RefCounted

static var level_data = {
	1: [
		{
			"id": "mito",
			"img": "res://src/karakter/selImun/assets/mitokondria/mitoIdle1.png",
			"title_id": "MITOKONDRIA",
			"title_en": "MITOCHONDRIA",
			"desc_id": "sumber energi utama yang menghasilkan sekitar 90 persen ATP (energi bagi sel) lewat proses respirasi sel, tapi juga membantu mengatur keseimbangan sistem kekebalan tubuh.",
			"desc_en": "the main energy source that produces about 90 percent of ATP (energy for cells) through the process of cellular respiration, but also helps regulate the balance of the immune system."
		},
		{
			"id": "atp",
			"img": "res://src/poin/assets/ATP.png",
			"title_id": "Poin ATP",
			"title_en": "ATP Points",
			"desc_id": "Poin yang dihasilkan oleh Mitokondria untuk membeli sel imun.",
			"desc_en": "Points generated by Mitochondria to purchase immune cells."
		},
		{
			"id": "energi",
			"img": "res://src/poin/assets/Energi.png",
			"title_id": "POIN ENERGI",
			"title_en": "ENERGY POINTS",
			"desc_id": "Poin Energi yang terdiri dari oksigen dan makanan yang jatuh secara acak digunakan untuk membeli Mitokondria.",
			"desc_en": "collect Energy Points consisting of oxygen and randomly dropped food used to purchase Mitochondria."
		},
		{
			"id": "eosinofil",
			"img": "res://src/karakter/selImun/assets/selEosinofil/eosinofilIdle (1).png",
			"title_id": "SEL EOSINOFIL",
			"title_en": "EOSINOPHIL CELL",
			"desc_id": "Eosinofil adalah salah satu tipe sel darah putih yang melindungi\ntubuh dari parasit dan penyakit serta berperan dalam reaksi\nalergi. Dalam game Eosinofil digambarkan sebagai senjata yang\nmenembakkan peluru mematikan dari jarak jauh.",
			"desc_en": "Eosinophils are a type of white blood cell that protects the body\nfrom parasites and disease and plays a role in allergic reactions.\nIn the game,eosinophils are depicted as guns that fire deadly\nprojectiles from a distance."
		}
	],
	2: [
		{
			"id": "epitel",
			"img": "res://src/karakter/selImun/assets/selEpitel/epitelIdle (1).png",
			"title_id": "SEL EPITEL",
			"title_en": "EPITHELIAL CELL",
			"desc_id": "sel epitel ini memberikan perlindungan secara kimia, fisik,\ndan biologis, sel epitel ini dapat ditemukan di berbagai\nbagian tubuh. Dalam Game digambarkan tembok kokoh untuk\nmenahan berbagai serangan patogen.",
			"desc_en": "These epithelial cells provide chemical, physical, and\nbiologica protection. They can be found in various parts\nof the body. The game depicts a sturdy wall that can\nwithstand various pathogen attacks."
		}
	],
	3: [
		{
			"id": "mast",
			"img": "res://src/karakter/selImun/assets/selMast/mastIdle (1).png",
			"title_id": "SEL MAST",
			"title_en": "MAST CELL",
			"desc_id": "Sel mast kaya granula dan  mengandung histamin dan heparin,\nberfungsi dalam reaksi alergi, dan berperan dalam mencegah\ninfeksi. Dalam Game digambarkan sebagai ranjau bom saat\ndiserang patogen.",
			"desc_en": "Mast cells are rich in granules and contain histamine and heparin,\nwhich function in allergic reactions and play a role in preventing\ninfection. In the game, they are depicted as bombs when attacked\nby pathogens."
		}
	],
	4: [
		{
			"id": "nk",
			"img": "res://src/karakter/selImun/assets/selNK/nkIdle (1).png",
			"title_id": "SEL NK (NATURAL KILLER)",
			"title_en": "NK CELL",
			"desc_id": "sel Natural Killer (NK) melawan sel abnormal dalm tubuh\nserta serangan akibat bakteri, virus dan mikroba.\nDalam Game digambarkan seperti sniper dengan kerusakan\nbesar tapi lambat dalam menembak.",
			"desc_en": "Natural Killer (NK) cells fight abnormal cells in the body\nand attacks from bacteria, viruses, and microbes. In the game,\nthey are depicted as snipers with high damage but slow\nshooting speed."
		}
	],
	5: [
		{
			"id": "fagosit",
			"img": "res://src/karakter/selImun/assets/selFagosit/fagositBomb (1).png",
			"title_id": "MAKROFAG (FAGOSIT)",
			"title_en": "MACROPHAGE",
			"desc_id": "Sel fagosit akan memasuki jaringan yang terinfeksi lalu menelan\ndan mencerna semua mikroba yang ada.\nDalam game dibuat menjadi geranat dengan cakupan area luas.",
			"desc_en": "Phagocyte cells will enter infected tissue, engulf and digest all\nmicrobes present.\nIn the game, they are designed to be grenades with wide-area coverage."
		}
	]
}

static var enemy_data = {
	"virus": {
		"id": "virus",
		"img": "res://src/karakter/musuh/assets/virus/virusWalk (1).png",
		"title_id": "VIRUS",
		"title_en": "VIRUS",
		"desc_id": "microorganisme yang meinfeksi pada tubuh untuk bereproduksi.\nMusuh dasar yang datang dalam jumlah besar.",
		"desc_en": "microorganisms that infect the body to reproduce.\nMajor enemy that comes in large numbers."
	},
	"bakteri": {
		"id": "bakteri",
		"img": "res://src/karakter/musuh/assets/bakteri/bakteriIdle (1).png",
		"title_id": "BAKTERI",
		"title_en": "BACTERIA",
		"desc_id": "Mikroorganisme bersel tunggal yang Lebih tangguh dari virus\ndan membutuhkan lebih banyak serangan untuk dihancurkan.",
		"desc_en": "Single-celled microorganisms are more resilient than viruses\nand require more attacks to destroy."
	},
	"parasite": {
		"id": "parasit",
		"img": "res://src/karakter/musuh/assets/parasite/parasiteWalk (1).png",
		"title_id": "PARASIT",
		"title_en": "PARASITE",
		"desc_id": "Organisme yang menumpang hidup pada tubuh dan sangat merugikan.\nDalam game merupakan Patogen raksasa yang memiliki pertahanan\nsangat tebal, bergerak lambat, namun mematikan.",
		"desc_en": "An organism that lives on the body and is very harmful.\nIn the game, it is a giant pathogen with very thick defenses,\nmoves slowly, but is deadly."
	}
}
